name: CI Build and Test
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      
      - run: export GO111MODULE=on      
      
      - name: verfiy version
        run: go version && ls -a

